export const currencyFlags: Record<string, string> = {
  USD: "🇺🇸",
  EUR: "🇪🇺",
  PHP: "🇵🇭",
  JPY: "🇯🇵",
  GBP: "🇬🇧",
  AUD: "🇦🇺",
  CAD: "🇨🇦",
  CHF: "🇨🇭",
  CNY: "🇨🇳",
  HKD: "🇭🇰",
  SGD: "🇸🇬",
  INR: "🇮🇳",
  KRW: "🇰🇷",
  BRL: "🇧🇷",
  MXN: "🇲🇽",
  ZAR: "🇿🇦",
};

export const currencySymbols: Record<string, string> = {
  USD: "$",
  EUR: "€",
  PHP: "₱",
  JPY: "¥",
  GBP: "£",
  AUD: "A$",
  CAD: "C$",
  CHF: "CHF",
  CNY: "¥",
  HKD: "HK$",
  SGD: "S$",
  INR: "₹",
  KRW: "₩",
  BRL: "R$",
  MXN: "$",
  ZAR: "R",
};